---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBDw9nTAHElLv0NSr0wtJK+lW8I4mkbTBW/lX9AaK1f0Up+WUKiYDmtMRH8PNebbvG+csj+eX5PSCvadfvqbiafPL1nNIo1f71Umc57rcXj9MGgfWs8Tn8UtjjjLW3csocVsVTGhAvVV23CL4lWL8ZkB8thCsnmFWSs4NU02AkI4c+xgyUIOcbOb+fRsMFdCSvWBn8HyL8BA7l0UOiWH6IvKvruWHyeizw6NzpEDmJOPP4J76xtVv36mk75SHrvWF2dXaxVlBfZ/M2YSJRtPVlUMcoyo7Q950qIblFulzK98al1vySMqZpLHWGeAHFv7eMfiHVtw0IRf6Ppn3f9DqcwZrWuDhZmCpKdGqpFZsC4zwZxsyk7mBvcjRvcNXzeFNXcfrjpqeQZlOKsw0at4YW9MGPJ6pXLJZKJhelEYsZafhQMnK6wN+R98IIwUV126qHnpTY8WpF9iM4DX//XztHJggnZZ029Lykzhf3CMgnJAVX8tWxGLULw5ms1wCH1eOFWNPn63/ZvUv5X9FgbI1/C8TxMc5z/74/EvWMVlrU8lb7sUafDJ4VDHywdhZre6TlC2tSGhbrxeASr/5tEqxXYbR63R9msVIwJ1oehd2KxFUhsDwL8z9utUdDiGD9fgMGSq+y1mRJ3Vf9JMJzD5ObNgAIVQ6HqpoCoKtZnddDMFolZAVUdgyNDBIkSKkf9DVuvBz21OvWDT1iPo5bFJnARwD7HdyobHjfu32RuYhRfVVUJkGANmD4sS/FdFO6/5Xh2U9viJku93agsIbP3d43tV9B5t3DFGzLRqCneNqNpm7i9ixDJSv5K1PrAcQfM0O4U5ZAocFYEJAGvSW8cSRVHOuh+dKOZr77VGyt2eSwfPQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
