---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCqG3GjMYc2i4QgXUxLFz1k4KwMr2kP0qwB9+btN6L/6Ba9QxDdi2V7CGaWd0RZ4UjJ4aJX5x6JIDOad3h3vpCOOFiDNqaZzfqk1pQunQgelTmQ8W934KDoYU6JzqrZzNEmyZ+mysVsBMbenSThXHIwcxa1+IpUrayN8aFM+Ebvd3p5OsXaEeyRuc+A81KL+24otAvhtm8sSzG0L6N73GaXXnihkNXUH6V+A07+EisuSv6t9sRYVEPnTJ5m+nF/GarGIkv5npSvRGsJ7GMkvlLuKb0rqcgslsd8UkDfraxljjtsAT9sW0uUC8zdpwOkydoaxl9b6xZCY/JiPzFN04R+JOx4PC9DhKhfEznohtVU1PcBesNND0em5z593hueuH843kwQM2ho8Tq/EwEZqYH7xGxSDzbtLXb9Eu5AS5FH1Lqxah9bdwULgVkljV1nXs5ChL3tW1/BGJxRbK3ZN30VKv8cOnLbaeZKYqCt8fmOw361jtyPdXaGqYyfQOee9qHH5ELsLw8qut0nbstscyraf8xoEoiLaz1ShQY7bdJavZ3JMhdAplk0nghRt8Z1nZnaUzf3HqfMCSLqLh1uWbOsmUkDISFK/LVDKVcseNrRQlc1hNnqCoPcA9rzMlGIQgGB4cDJiCkfwbaunvkZ0R75f886zxnSOgiIW6t8f4V21PeHNRaPHaz5d0ov+Fh48p3wugk6WkGDW0GzsZP9oSZKcaIFxLbYwmjTyJG57WPEL9YT7lXRBP1gP3tIaWUQgm7QnX7jQUXZyy2WPI71oUnSyReBuPXsFjTpgFQSDSz11QG633wwxtOe+nAFj3RPqJOnJZV6Wu0v56WXp7PTqv6HnEb8jR5PyeJ6Q5X3jD9CqqEuY0Y=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
