technicalSecret:
  type: SealedSecret
  githubSecret: "AgAXIC2d0O2BUekfvErOEHeyMUD+BTMfKvRt+oN7SQUWy9vKVOyXB7uICfV+b6SRVkdsE/xUuoXNqc0N43sQaCLX8AurIK0Jk9Z4cC1RvTs2XeoF7yhFgorbTODn7d8JR+B3BR5eDPbHNoyzXyXxIEko66V9LS5zDllet2frpyxjJMWR557aWn20+ovOz+uSAoTAkX0eF47PhtO9Sk3pNYzks0KDcGKf9Y59Py1GuV0aRnlsu6Z8CE4vdXM93YassdkJIa/XMH1QyUV0bt+Hsfk7amW2cyrIrvOYAWtqrsi4n5gN5ZzcZ4SResuUY5J6fIXx+RC/QijIFUeNqg8anmFL7YIj7hTDpirW9gjl763yJGroxG28qFL5OQVh0ZUkWcJSuGN8pbuDOzWtx45RLonB1SjZgsXNMZ+OcjoHGjj6dux2A4G8NH7n5GSphJfV7wMp1vDvS/BHYLyKCJbCXZEAk64UL0SvCmLfSKYfDykpE8QIwC3IBJGD8xC2+7lK3veG46ZyRSRCkrpDudAi/Rzuc4dTmQV0VI1Ph//ZGJNBG5ChmOSmGxMbJhvKV0x6ou4WaDQS2MpdKb4dx8EpV170sQ7bx1snq99K011fOZ9Ueah4dYQXnsKQHgNKDEwpwYgzlmx81Q6GatdMMnEZBbswAghAK1qwM1rMLnC+gBLFdTgAIGbgl8QR0F3ixwSv3mUA1YSGXf8eI+PCv/RTH5sKkgDMwp9neqdVEKuHmV/Kz2XNvvVt5ldZrl/rdIqSeXOX4OpUdUeVLb67MWT6uYFIVALOTFQprJlPZgStP5twCsgjG9PyTGeUD8ZgITWebA/C3RS7/jB9hcdXol7yOp0OacTckDHsigJBRZ/x0KKMtqR3valuotbRWSXgNdPUoGZWxXz/07QymAvAJY7Tfk2HMfkW6ZRA5w1nEyNeRUqLPzvzCI15XPiNhmQ="
  
module: react

environment: generic

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  imagePullSecrets: 
    name: technical-secret

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix