module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix