technicalSecret:
  type: SealedSecret
  githubSecret: AgAIpJmX3J49/wNaLjsEIi7H2tNC49daifl5er9s8EyDvswhnRRq7wWXclyhmHr0epTgTI6r4jT8uZ6L0N5mgoMnkyHyay4SuKRmkq68UbQ/GldlokJE51XurscmZfCB/tTYxgrBofsFdlsFUnQY9JrY4pDnEc3WLIGoOh0kSAGMR9pvm0XBGGxz4zQGFyU856n29omDbHOXNT6yORdQG0Qofu3jCWPo18JxfsmSYau/4TVuYeOkHjxMG/Qah8Bwbvjh1aEv2xCVYrKw+4rnCqtM/Gzi4RB6E2ojFq4glRTbvU1Hd9n7QUg9VThwAC+wkp3pqFB28ACsdj1IO/eTPPRlcwtC+057INZQVrBmAnGiTMyhzEuS6u8w8pqAzXxZNxb0WIAvRoLj9fRhwX8YyDsoECWclQMcV1wwt5ClOpLB5aiKm4uOeqw+HZN1FEutDum1EMcx5UoVdJZZRJ3rq+i7or7gDKT4yVDiboddmD8/QQq3hdPSqSgZ9GTqlJf3v2NWc6caHim/Ut8fu//XWJiuNkq2Ouft+QyWgV8N62lpPI3wip9CukEtLzy/IaG+AHj3BHPyTx0Xw0/nWE7N9/CosVOqAHNumyzXcxmiJc6Ur5LKwLuAO8woFteU63auEhCBi2rscYXkII9SMng2yi2/nR/B/t0FhFZ5J3mHVQY6IWzBmuxeFiEnG0Xs04z51shKp04M6Ox8GH6moTUuMrI7MmKLhZ7fwn5fzxA2AjcgvVWInCnhoRKtT8j+vliyidd5Iyo0m6u/vvW9BSYKRHvju0ciYrWPfVMa4GQ46qmLqhidvBnL8pTyAB9c7uzhVn3894RMAWbUqcsWa5RZLJoZX7aamvmYtjSZw9CADJQMJ2Acym/7rhXp5n1nE5XiVSRaYn4zkLT4/j5SFLk1/U+6dnrfhtt8


module: react

environment: generic

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  imagePullSecrets: 
    name: technical-secret

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix