technicalSecret:
  type: sealedSecret
  githubSecret: AgA0V6bkbUFqi2uIY1UDVq+tAAkuipk1huWNcHDQkTkCvNKQRh6+JB2E/K7yCrM8QZIvpy72TrA1Pfqu8jXOdzvuGFjtz2+loenCz+Y1KwhSbZMwfzuJTmaa4MH05LvgK9sKGpXo3a/vp2man52wK3cw6P0UTIpjyyFej3TUyPG96uDmMue+a95ZxT++fwbOWfnQ/Um4wMin1Tg9ax+wzGBEl9emQw7ruDzI4ccPz1IQxldodZjQKw5Uj+Z5gpHIWXaxg2j2l3XdJJAQJrYuUkmBLg+37csaQ+iuxwX0a3xCNXaGtpeZqqhol/ekHB7BdWL8yvzDqpB0b+t389sENzCKynTAET60tjN3cn2aXuE/JPHZkM9MC1X/7qJRdAguW7gfDEzvmoEqnBlubMyY18IGPsBIE+yZifkYu29FB4+JJ2XchPLraWtVXYvDs2c5e22jyPxDQp2Vx9akLQIuQvTy8V9UfB/rde8JPyZ61+ncidB4qTUlhw7BDYRlvtV2ZYrsTOZDbkzhjdDYT33fH78A41xKA/Lc5CG4rCf5ffN5Y5rjo9hHDjsBNi/qX20Sx774pkqmYD7DIGZmvZldnRnRDGc8krhB9+6BAcEJA9FhFbTdM+Uvx1ZG8Ba53xeZO/t4JP3AhYN9tq25gJrS6V9aoLXeDJTAN21WrqwD2MFkpLIzqfsikBtqSjenO90/nG+09NMk9vbu3tsKUcPHtFp38SzLTXjZz3J7l1bCLiE0G1kO0dIOB/c40Q4ujA0NhySJwHbbu/VuhuCuUVVwYf5HyKBXf/dxoC8MbL0IYga3B3MWf/jN
  
module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix