technicalSecret:
  type: sealedSecret
  githubSecret: AgBqfWI7bVoF4Jv2tKaVLo5reglnmJJPJJlTvy6AcSdAjQNM2cKdXg66IvMbEsFj3j6OdHx9nL3a9eYjfUbJ4f44nPUVAxLVoLDNNpgPAJPAMRPRjI9YYwsZa5jjfgdTLsfBbXvaf0wCxtvcTXnTn47+kAjbZj6E8HRZaDPgzvDyxHFEeAezoC60y0lHRo6ZQAxTg7g7Sv8C9sB0QN7bW9PSdRIkkx6SL4A2V8g9GJBklUKG50jitCz0B5AE6zVvlYpxYE3ai1Z7yA/2NXBFg3sBOqd1qTYUeAQi6/Ahp5X+wPGB87bgTBvUEUioMgFwy4eW9vYsHqr758Pt0SAJ9eXfDMCii3mIjQMXFKEjZ0P2PNOG1yajMp63JdfE9wL6CzgEMVPjmyDhN0fOlytJZgVxIDXb4QWcbcrUQ80yxyxD+G0L7qkNsbzvZ1IM7DyFI/GQXfwIwDw8E3OwaG+9lLLCLo5co1bN6/VPRQpiI7Qx3A4W4vPQeKN1HuC6yLaXhMA/MOXG9U3NYzU5oyVU9o6sU/Figvb5qHbXcLV1XNRj3C1wXTpXVNKWvHpiTtm1tbubPofFnZ1S21a49hmnCmxzlt5fYZcw7Pxqxs1Lk8tCvdeMophcur4SBONr3T0H3NQiIuUkbPIrakjtpWXx4j/TTtnBze1+NVJChstwU1PV0geEcDUSReJ9MJyZdmiLNbh9YU6rKImsaqY1KUtxsnjEUN/bgp4tWDigPh2efvql09UfKZ/xqv/xhTi0pz3dJTw7oFTcJRP42QRVhfFeQp4oJPkFtsnycPh2wxmiO2mU2bOOHqfpnXhulqfJirREaKMgZXtqF0ScvnD6NZbdygzKT20LIQctUTCq/9QpICop2jw/IUQVxowyJ7OkTV50Dj+2pNnXESlG7+6uB2LeVYW7XNE/uF5gc1B6LdZEXw07FYvtwe+e9T5MwWA=

  
module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix