technicalSecret:
  type: sealedSecret
  githubSecret: |-
    AgCVrjW3MqWY1TfXMm+RR3v2yFNX6GYTUB1s0QZLFiHGEINkpDJouja08xJaXNmUQazkWLzRvzHzmH1Sz0TupoGCjk+Oh/LuU0XYk+6zPNEcodHiGBKjZACA/QqEYDyHCg1TK4DUhET3LVAqWkPzghyQiq6zG+ENpeTmGW7XqJR+cQ4X1njcXsJGKO9NZVWQ05FUpv+xM0leJLjoy87+7mUssq3EDgkGh+EPP3Oq6CluDnOkQ92d7u4GWFE24QNeapgMaknlCkMMHBYIjFaMC1z165To94P6+DS65iIuVREfDFQJxUU6+zbE4ozOOeB8D5fGfyO6nnwwlH2RuJO9/KkejSjESjm301Vh7fh5shBwwwEVUIwcU2IZ2uQeaA7OcgHAZXmaD+ZyJfAgrfMKbeBrYn0YAExYHoT0BthQrCRp0Y/20PvIEJRRl1uJXKx6JE5e+t/LVi2a1iPTG5t/d1Zdf29eTYesOrJ35/YbUMf1qJs3s5sOWxVthcU+P1dwdm0H/49hWMhmE3WmHWquuS26s4TVhL3yJagGkYzWgtu+B2spICYxVRH5IGd8uY/+GV6ga86BRPB7WGDcH6qlQ6SdMpjx/GBcWiz21FbG3m7VqfJUe9alYf4PfdqQ4nHrtZrU5UXI1okbqlLbIVWC6fyh3fCq7DpSWqsvnm3HsHXhhJUbu5gFpQw+UtlRJAXvV5HL5SUJ49h/pBcRevSHRpCn6E4u08gMa28vBf4fqME7vlsyKqSw4XGhZsvSAfBeMXS7U4RJ5iq1x8vCBwlAYF+r/MEttnndAn969kbX+qIyhwCBaVU3LTli02606B6EhlHnFYynUKiLqyTNyQfT5UHA4RR6jWeKD59kjHhfLTPu2jtTbnLDHiY2GK8UPmpyeFcbmhkqeO4spckvB4QsVkxwuZO44qTorLpJXo+nixygUI9Ui+L2PmEBc+k=
technicalSecret:
  type: sealedSecret
  githubSecret: |-
    AgCc31PqFfDtbBNHwfjJz1e8K2SeFotNY6SavTOP+K444eF+bbip79tIRP9vpSlyKZInKmWrabz30ewXo8m81hbi5mH5/p7iWC2grOPgh78vW2bmE8FvmqlpDJ83ofSlkeXyEqU/waBaxDF9e5U/JVjC9uqjG2HJJQgF/8aqaVDDdkLVJ/BKHCV4qr1G9kLkE/tcw8FuSolzeHwEFv9/DefF0VN/mzgJ0UvcRHCp3AVE/1C5Hj1YzFTHA2c7Bp/85nJx0x2A/4SyXhBQS1CsLuadLnLsGi6tPIeK8oc86YDUlvvtSG+lPKOWuCHvRsl/9G0eeIFwiwJ3DJ2IhXD6q9fxmzHXbBLh/4bhVXHKG5S/ZM3WQGVSplVjqozlVQ+CmflTv74ghaay8lREQ6mO4EIRfUDLpBFUcMhdwhPP5+7LUgAr5XhuUeHAMYXIDLEw20CI/LKDUhUwr+OeDje9XVxR6vpI319Hgdkc8BW9iaR4E8ZFR2cLNsZU9pCCKBcHiTiXkwy3DGWXoNJQD8nObOLhw/btvsvFUF8H7QuzQKoxig7mhagPyv7GniXjtQM7y+Zqgii7ndOlRwxFqlTDiq/89FJtLMqRP4sw4w0AVsM92COoTpkkl7svpgMgZvyNOhwCLl9q8cQ1Xxt4R5gPCs03bMl4ijULoOqq77GQTbQ4q/8wSlPgIWC3h0ky6wlZ9PPTiALEajQVG/L6nkx8mRzreAeLD2QP/5/O1w2DkRaw2itYzLvSU6XP4oWd6BvrcFz6fK0JteBhBB7m7HP21Lh2q5VSm6cQkTxPZxDBgpr2H6TKqAk0AksTqiqPEsbgsw/3BzGQTa0jvsQqjc/j+/VoehrW3cBp6EUNlYzs20ybcU3c+lYdm02UpunMIFdll13PfKEEfrJNYRy9ibQ6267PpFeXI2SyVcb6c4hZxVBYfUiyRMmgmi3dRY4=

module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix