technicalSecret:
  type: sealedSecret
  githubSecret: AgB8MirRYF3OQsV6IJswlMFbkj9muVPcUpF4ZHjpj/8bM/mhc4WVMdnSMpIuIThIGkMvyylyDuk230iJd+tSurV4QpLCgx9G//Zs5I7exB6oHRjyMyp/apWroWvZ4XFuNZnwIacJ9BT1kJwsavBumyljs7O3+JXTYS83uKxX1cH4ie2UaIYQXP31g0MIFuoemqHhrv27cqpjlYSuq7QhYdeV7PV3wirMFExDcFB/uwqjKdA46pWMsF57W6LvNNVwWssUM7LbzXsezXRMYuAU8JYaiT6kJZUJ4abAGXulCPeQ2RbKcdGRwdVmaADsMjNgLoWOX7TwfPmLKY8AJ6fH7iPZguEGO5XDqBrxoEqT3nIGePzmd71hBv6ouEHYq/4Yid3rBJa9miV2naGIsthABnECZPN8azXLzc0B5YaRHq/fNylakIy6fncl5Z1H1b6JG/fvcccyQ254ETVa/Ms59/NNUWhPiJmrhqdnK9hzTEu+7/8u618FO8KU3+YE2NjEZgKsBmvC1JV74z+nzPipLQ+ujeG3IGewZAbgEFyv4kBnWPRjwttwWGtd6oEzeRfl6lsEvA2H6uL52PbC3N40y0Wa569Q9Rz88TQVQem5PLoBN5KywZJ3HRc04r+BM+GhnOhdB+N3quf2JDHhjCZ/mwowN1qKTtGRQFWvtkEmSuz2a8f1y4FXSQhebjNrzbSd6/HniMZ7UFTFzO5Er/YTatY0wpcHxk6XFMmheXaK7ITj3B3Q1VWosy1+J8+6y2XXGW+tGf3loy+B22JoR5a51pu1qrcpKKxxg2ZVPi34mHpMEFfd6gp5CsIdJd8RUSecqkUkl61VllV9Dn7z2VPUf7tsHe1sG3P+GpF7FvDQtok+MevOXk3iyaRC9vObs0A=
  
module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix