# Configuration du secret Docker pour GitHub Container Registry
dockerRegistry:
  enabled: true
  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUV2xzWlhSdlEyRnliV1ZzYnpwbmFIQmZRbFUxYjBsV1EyRlRPVWRXT0d3MVlWaHBTR3hCUWsweGRuQk1XRFpNTkVjelJtZFMiCiAgICB9CiAgfQp9
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUV2xzWlhSdlEyRnliV1ZzYnpwbmFIQmZRbFUxYjBsV1EyRlRPVWRXT0d3MVlWaHBTR3hCUWsweGRuQk1XRFpNTkVjelJtZFMiCiAgICB9CiAgfQp9
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUV2xzWlhSdlEyRnliV1ZzYnpwbmFIQmZRbFUxYjBsV1EyRlRPVWRXT0d3MVlWaHBTR3hCUWsweGRuQk1XRFpNTkVjelJtZFMiCiAgICB9CiAgfQp9
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: 
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: 
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJMVzRnVFdsc1pYUnZRMkZ5YldWc2J6b0siLAogICAgICAiZW1haWwiOiAiY2FybWVsby5taWxldG9AZ21haWwuY29tIgogICAgfQogIH0KfQo=
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: 
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: 
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret

  
module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix