technicalSecret:
  type: "SealedSecret"
  githubSecret: "AgCRFZTBf6UUeHrFA8B6oRNzYH26GIMaT5bAai897sXFaid/y+BxGWwZrlhhzolfDmYsyDAjwt8DLCfuJO0qavIYosT1zn50VMdR26hQDz41puKBSHQU9F1giwrWVG6u7AVCpdHkPgONOeHY3/G7SgWx6LcWiRyq05J8CMr4tWlTWyH/YGYKWUbs6Xc1lbsSdRDiSQssSe0J9V67iH/WmPDo/9R+iQF1Tqu6ZV84MAlK0vnHaLQ5uDGHA4sIAfCvh2RCE4QZJ/0Z5sDmc8weF+eLP+K1khHpUflCRyJryzw5mnrpftkAcZWlBNsRG2Uzuqa8lPd0Z2x/BxCqqD3uZp/N2n+gBt3L7E5uSrfTPwGxEdfuZZRQKd3Cj5HZ2NhNdJ4QBc8r7N9vFhjDmOxavk53J3la3Pvro2Nq++HL9uYGdbzgAblwuTEV9RkjX5X8KgnS31QtjygppNWJ4UF4X9jszLI8NCl43ECy8WpeN5RpIpnz2R/BLA6i/dF337fUCri53A9PwaYiNyK+WK39zjclWus0d3X1Ff+92PiYmkCRwrqYVbhqsBo9uxOagQkzhMvf7+foi6P5Cdhayo1wN5LAaQo+/KrFHxQmlsILml3j3I57JcqoAUg6uFvwSkvjuZUD/MjDnYtjnvoRm7nHLhwTA4oh+UyczZdZ6c3R9Q/RvUwqtJGt5deJa8QFtW6GjxQeNiaABgFvQWWHQjqFkAab1sCNJ2u/NVjQFqbF5Uzt0xAOcQFA1aqI5/ouHedgVPRr6W4h+Ol9m+bt4vmvoCQ+e78QbU1C1btzUuM8mAEfPBhX8ifQPOK3ZfCGFNHhbP5pdKJJXBCkZ9FItoMMMAPw7o4uuW5czJT2LaSm818lEBFtKvCKqLwB587Nyh0bmVhxpfNe4WJ7jSCpVrvYU1An832H60KPnZpXh3g/zPPiKUgxJ6Er9mzHnrJjEWxbF6/DJS6Pl0QbqNdGAje4zPagrvVR9wnDzNqJS7EixMgo1iu1r6i5dvO2UkJDm+SsJow6"
module: react

environment: generic

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  imagePullSecrets: 
    name: technical-secret

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix