# Configuration du secret Docker pour GitHub Container Registry
dockerRegistry:
  enabled: true
  secret:
    name: technical-secret
    namespace: dev
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUV2xzWlhSdlEyRnliV1ZzYnpwbmFIQmZUMFZFVEVKRWJsSmpNMjlaUVhkTE9EUkVZWGswVm1oNk9YcHNORUo2TWpnNVZXUloiCiAgICB9CiAgfQp9
# Configuration du déploiement
technicalSecret:
  name: technical-secret
  namespace: dev
module: react
environment: generic
replicas: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
    path: /