technicalSecret:
  type: SealedSecret
  githubSecret: "AgCEMykT0zIo90moIYoNh6k0gwoEKNoJ2wpdHe0SqGrGLYP7w31zObhApn9IwSiyJLVb6r2xDPbuLF2BdE+hhXy+a/AjXQNwKFDWqef64XjANpWAXOOGonmkrSOUAQLGd/Kj3G0dIU45sjFCnshSHDlE9rxwk0MFyDZeUOltmdqP9rJLxMj6aBfkAm9OWAPKSAth2OdBqRXy1teN6dKRfaxcoaIoQ9nDliQLkQoUaPMliforSulqpHboBJ2Jbnw9Bsku9jIaZMAPPgUFlH2o1X9dZKqzI8aKGaGuVyHl+tA+2Wa3zajN8dEL6BQVobPZUDxSy9U4Pzm2TfVX3h/JEs46EuUTUYKhwA5VVlZby1FSNYtdNDz4edAa4XFvWCskL5Zqth9xWYv2kUL+MLjy3QwKD2/6/5x6JdcRZMI58L+fOsNQdk2KUSKt0Zq/l5xDfk6o9Rm/eOqcYBZTu9T08C6r8xQumqLzm0l8TSGj64UNAI7vS0rB85a10YsxnvrIXARL9dXS+NyDpP/y8oWD3Qh6PRG7qrNUfbW/p6tJ+1aP5jOKWUrCOZL62f5pQz+4BdqUXNikb685ZKXhn1LnA4/j5876nWOV1V7Iqs2lusEQM+aIDn+OF5AUhJl80aXw6SRcFX8wKCuTHtWFpzpWUA0f+eBEJWE0/ziP8VxlEN8u1c0veJLrRSZM/1cK+Qf3pHnny/3fG219RmcCB9spk85bTp14Wj3qzX9JXy9RqQPtL6r4uNTEffMl4h/p4PWItPNejJAv9FR81bV+IDDzGARh6SONePUXtT0Wa0TV+TVW1CH4DBtgGk73rVOjiMFS2Yoo3ovvsVTylgVKTSTe08+igh6GwIljEXvQCcEjOtWDnWhHs43SHbbtfSc5/srjt6qy8Ezcxcyu/3MKOESVfYwtUnAgfRi2k2H+HKb0iBoSE/5bA4yz2C10uOE="
  
module: react

environment: generic

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  imagePullSecrets: 
    name: technical-secret

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix