# Configuration du secret Docker pour GitHub Container Registry
dockerRegistry:
  enabled: true
  secret:
    name: technical-secret
    type: kubernetes.io/dockerconfigjson
    data: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJUV2xzWlhSdlEyRnliV1ZzYnpwbmFIQmZZemgwYkc1UFdXOUtWRFp0YzBZMmFGaE5WekpyY0doclQzazVZblo1TWxOQmVqQkkiCiAgICB9CiAgfQp9
    
# Configuration du déploiement
deployment:
  imagePullSecrets:
    - name: technical-secret



service:
  type: ClusterIP
  port: 80
  targetPort: 80
container:
  imagePullSecrets: 
    name: technical-secret
ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix