technicalSecret:
  type: "SealedSecret"
<<<<<<< HEAD
  githubSecret: "AgCRFZTBf6UUeHrFA8B6oRNzYH26GIMaT5bAai897sXFaid/y+BxGWwZrlhhzolfDmYsyDAjwt8DLCfuJO0qavIYosT1zn50VMdR26hQDz41puKBSHQU9F1giwrWVG6u7AVCpdHkPgONOeHY3/G7SgWx6LcWiRyq05J8CMr4tWlTWyH/YGYKWUbs6Xc1lbsSdRDiSQssSe0J9V67iH/WmPDo/9R+iQF1Tqu6ZV84MAlK0vnHaLQ5uDGHA4sIAfCvh2RCE4QZJ/0Z5sDmc8weF+eLP+K1khHpUflCRyJryzw5mnrpftkAcZWlBNsRG2Uzuqa8lPd0Z2x/BxCqqD3uZp/N2n+gBt3L7E5uSrfTPwGxEdfuZZRQKd3Cj5HZ2NhNdJ4QBc8r7N9vFhjDmOxavk53J3la3Pvro2Nq++HL9uYGdbzgAblwuTEV9RkjX5X8KgnS31QtjygppNWJ4UF4X9jszLI8NCl43ECy8WpeN5RpIpnz2R/BLA6i/dF337fUCri53A9PwaYiNyK+WK39zjclWus0d3X1Ff+92PiYmkCRwrqYVbhqsBo9uxOagQkzhMvf7+foi6P5Cdhayo1wN5LAaQo+/KrFHxQmlsILml3j3I57JcqoAUg6uFvwSkvjuZUD/MjDnYtjnvoRm7nHLhwTA4oh+UyczZdZ6c3R9Q/RvUwqtJGt5deJa8QFtW6GjxQeNiaABgFvQWWHQjqFkAab1sCNJ2u/NVjQFqbF5Uzt0xAOcQFA1aqI5/ouHedgVPRr6W4h+Ol9m+bt4vmvoCQ+e78QbU1C1btzUuM8mAEfPBhX8ifQPOK3ZfCGFNHhbP5pdKJJXBCkZ9FItoMMMAPw7o4uuW5czJT2LaSm818lEBFtKvCKqLwB587Nyh0bmVhxpfNe4WJ7jSCpVrvYU1An832H60KPnZpXh3g/zPPiKUgxJ6Er9mzHnrJjEWxbF6/DJS6Pl0QbqNdGAje4zPagrvVR9wnDzNqJS7EixMgo1iu1r6i5dvO2UkJDm+SsJow6"
=======
  githubSecret: "AgAIpJmX3J49/wNaLjsEIi7H2tNC49daifl5er9s8EyDvswhnRRq7wWXclyhmHr0epTgTI6r4jT8uZ6L0N5mgoMnkyHyay4SuKRmkq68UbQ/GldlokJE51XurscmZfCB/tTYxgrBofsFdlsFUnQY9JrY4pDnEc3WLIGoOh0kSAGMR9pvm0XBGGxz4zQGFyU856n29omDbHOXNT6yORdQG0Qofu3jCWPo18JxfsmSYau/4TVuYeOkHjxMG/Qah8Bwbvjh1aEv2xCVYrKw+4rnCqtM/Gzi4RB6E2ojFq4glRTbvU1Hd9n7QUg9VThwAC+wkp3pqFB28ACsdj1IO/eTPPRlcwtC+057INZQVrBmAnGiTMyhzEuS6u8w8pqAzXxZNxb0WIAvRoLj9fRhwX8YyDsoECWclQMcV1wwt5ClOpLB5aiKm4uOeqw+HZN1FEutDum1EMcx5UoVdJZZRJ3rq+i7or7gDKT4yVDiboddmD8/QQq3hdPSqSgZ9GTqlJf3v2NWc6caHim/Ut8fu//XWJiuNkq2Ouft+QyWgV8N62lpPI3wip9CukEtLzy/IaG+AHj3BHPyTx0Xw0/nWE7N9/CosVOqAHNumyzXcxmiJc6Ur5LKwLuAO8woFteU63auEhCBi2rscYXkII9SMng2yi2/nR/B/t0FhFZ5J3mHVQY6IWzBmuxeFiEnG0Xs04z51shKp04M6Ox8GH6moTUuMrI7MmKLhZ7fwn5fzxA2AjcgvVWInCnhoRKtT8j+vliyidd5Iyo0m6u/vvW9BSYKRHvju0ciYrWPfVMa4GQ46qmLqhidvBnL8pTyAB9c7uzhVn3894RMAWbUqcsWa5RZLJoZX7aamvmYtjSZw9CADJQMJ2Acym/7rhXp5n1nE5XiVSRaYn4zkLT4/j5SFLk1/U+6dnrfhtt8"


>>>>>>> refs/remotes/origin/main
module: react

environment: generic

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  imagePullSecrets: 
    name: technical-secret

ingress:
  enable: true
  metadata:
    annotations:
      pathRewrite: /
#  tls:
#    annotations:
#      cert-manager.io/cluster-issuer: nameOfClusterIssuer
#  host: myhost
  spec:
      path: /
      pathType: Prefix