apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{-  include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
  name: {{ .Values.module }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.module}}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{.Values.module}}-{{ .Values.environment }}
    spec:
{{- if .Values.technicalSecret}}
      imagePullSecrets:
        - name: {{ .Values.container.imagePullSecrets }}
{{- end}}
{{- if .Values.containers }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{.Values.containers.tags}}
{{- if hasSuffix "latest" .Values.containers.tags }}
          imagePullPolicy: Always
{{- else }}
          imagePullPolicy: IfNotPresent
{{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }}
{{- if .Values.containers.resources }}
          resources:
            requests:
              memory: {{ .Values.containers.resources.requests.memory }}
              cpu: {{ .Values.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.containers.resources.limits.memory  }}
              cpu: {{  .Values.containers.resources.limits.cpu }}
{{- end }}
{{- end }}
