apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.module }}-{{ .Values.environment }}-deployment
  labels:
    {{- include "label-generator" . | nindent 2 }}
    module: {{ .Values.module }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.module }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.module }}-{{ .Values.environment }}
    spec:
{{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecrets.name }}
{{- end }}
{{- if .Values.containers }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
{{- if hasSuffix "latest" .Values.containers.tags }}
          imagePullPolicy: Always
{{- else }}
          imagePullPolicy: IfNotPresent
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }}
{{- if .Values.containers.resources }}
          resources:
            requests:
              memory: {{ .Values.containers.resources.requests.memory }}
              cpu: {{ .Values.containers.resources.requests.cpu }}
            limits:
              memory: {{ .Values.containers.resources.limits.memory }}
              cpu: {{ .Values.containers.resources.limits.cpu }}
{{- end }}
{{- end }}
