---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgA4jtEYfoXBXxc1IgjUNFqfAuqBIJLCfGj5o86/k9k5oaszasBYK5jKvCXoAHHMC1y186DCd54L38PsKgB8mqgltdbi+c+1YzME8vrV82DokjUcj0gbji5Jn409eLTGZTJ7HCa/ryV1W9gxzAA0rRnR1/Y7KhrUDawY6gTxKYsOk7ZgK6xg/QT+56+WqljLGsD+DVIJRB3+xVUMYklDvWlylIpjbQH+7GDmZd8GILyYEQ06RwYjmP42Bq6qgMtn9a9pWhtfB6VM3cwgGeg0pov1Lemst/bOTkQUQFplsV327N5dMZMnhwDlzVtIxe1/t8h4YSjSrxQhZZ7E2YVpNuWEeAMQ338ZgxP1CuGWttMcktqsoty7LzcooG5A1CBAV4JIR94z1pPteqtCX1+HlWESjwIHJf0jh1Fov17PmV+I40v/p48qNc3Yr0zh/FFZoyvdOcUp2HloQWCF2U89EfzCBToeGCjriTcMBiasoB/TYXwEHRqS15Y4K/emDO+Fdfjx2oQks0R66iXYGK83FHbM4quyfsuggKOQFzE2xcibGgnOiu/yHcKiVNP77FxomNNjtSWiH+EmC7fNXdVYFAiYdY/YAmX2l3u6uygNzKaQNMb/3mRgM4ZhBb6CVEw93X+kkBeIUHf6wYNN4svFD8PPHX+O4ZFbjQ3cW2AUo7NB/rKNdEXFWpmsEP+rRw1KJGa7F0DUv84ia+OK9dJTxUVENHDMV8wpfvtX1gdIFaH5jyu8lfqkdoXFSoBvp2NZlzaSAZEPvT0rvbbxUnGjzdq+VLkCeBSY0sTPjXPjcjcXPmBrbCqsvJqrdlfQvORvhLpf7je7lfbCMi4YzV+uBEtiBVO1vbqeDv4wkzQycETMtDwQ/SMgkh0X43WQ5RlrWSJPdTAd9ejFQbra15vqD/1in0FzJi/C+ssy6c8jVAT2bTmESouI3psYvHA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
