---
{{- if eq .Values.technicalSecret.type "sealedSecret" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technical-secret
  labels:
    {{-  include "label-generator" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.technicalSecret.githubSecret | quote}}
  template:
    type: kubernetes.io/dockerconfigjson
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: technical-secret
  labels:
    {{-  include "label-generator" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- if eq .Values.technicalSecret.type "stringData" }}
stringData:
  .dockerconfigjson: {{ .Values.technicalSecret.githubSecret | quote}}
{{- else }}
data:
  .dockerconfigjson: {{ .Values.technicalSecret.githubSecret | quote}}
{{- end }}
{{- end }}


