---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCPYM2E8ce4nHdr9+0Ca+8pxLqDJ74ECvAOXlTPJjykGkT+Np3WaJpRYIA4Tk289aBBxnTEbxvH+CE2bcGfYjlejNQrIKlzck+t33uW/N4a1JqDGsWJfeyyGWCZqL4uiakYTA7AP+t8wmEt+JswaVL2/VT7EBwFRvMqWicD3GLPRTkxc3WIjr+Qnluy4kOXEjPBGE1ro8KzMfUmVvg8Ib013q1Qwq/Hg/KTT/HVc5M6GFozf+6qYszE77u/rSVBaRcwm5wO086OOwry3ux6Zh16jSWulnw7FHBJau/JvOKDnTUT04onWW6akGJFYSVr0WuAhicYA4K5zxUwESYCfzEiqzRoda6AB2MUKH7PL/PLJyHrcpEmGRYU3/WRt6l3KQXja25DNXG0aS3+aw9vz2PcIXJH8V2XHTJ7ImG6dI5RYBw8G8xAZwTSgsmVNdnmRJ4SnclB1G33OdaTg/4zDRvM9EiVFdY6a18N0iBeeDpu7Rf/lWnQOcrqeQ51Qvqvpy6rp4Cjy/g5svTqVUQvP8ZD09TAt44N1R6A+Felr1GZnDYLiPPr+GUfl2o7dpyVtTWjEi0HKLbIUPME4vhKUvNWlsAFFtjUrJQ9rUj3+IisLlKF09MV63l4wJWtbkH8uBcqRPHVZPVMfatKt24UQkVW91aYP8TCXxW/M2lc/vfS6Xl8ZSIyyyLoDAUkY5ZK5OhDbmWqb/fztMUFpLmJKl9Q3a0DyzFQ7pCLO3v47uCfcaJguKIsx14jM6yemZAetrcnBTBJQcPIR/D0WoREMo9AjkKdp9f44OdXYgbqOLvZNijBkMvfP3BqzTukwK+t/VSDnI15teOUDOLj1FmI2c/5SOIa/7YZpsZPaVC4d83O9Y9Z1D2yfw3zc46aIxYFFxI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
