---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCS2lRXQmu3OvRoOoZH1Zx9e+bx2r8PPX3slGmcnNOksH7sRNSRolRrLkQk2RS+KnMCerd09M1NSw/llv1zk6IH3yghhk3SEYy1Ii02YoSQlI6cfF5zEm77xwBx1OdwEn0CXMMEKjN7K+GZG0zcjRE+KH0kwadr6L9vlTH/9LOnDdTnhzT/P1ZSE7PhhlfGqFaMqGHgcau4q5xC/AmEpSri2w2MUjN0uMXWZDl39biQDfbqOKSfEvGjsh67770Q+oVGTLQqb/8MGPk3vz6ggTklp/ODk4zVU10qIO/qHlLtSdE2MVT9dbmuBkmCkHVdiMTC/SGGwO3eA8xlERFUwpZslZT6tFLttIzm+6e+EVi+0kYl9Z4d2E12ur7PQ4DH/ORJz7ClyJs9dqq9KNIVeNqLMUssHXd0ezkrKbiaFgNYCB9X4Ebu83lrC33D6kcfXQSa/978OfcumQCVNIJ3a9TvjSu2/ePTBNp6woc2Ko0DraN1+QYrhCVJdQRIBMaZ5rhztNIWhw07baUFJtEbdcB5DtOSs3SSERsuu8jdP94MwPkW4cjd6GSxtyK5SGH36/OokarOgGiS6itzMoFcKxq16hF0TWoApsn7/BbTZsljSvbPfvjI00Sbyqzf5Kl77avVUqy0fKRdXIhWvcLcM+yu5fE0hSec10rzJvfcPEfhGEra2OhxxOJCKMsLHak9ioNdi2HOS/2m9p6kcDiybfYnmnGUvjcF8hZkBM4vxbX+KsSLlva9W+NHdGW0TEIXUXlSFzbJr6yHLzAUbK1zB/i5r0PluOkh/IoUWKjc1MKyl/f9dNCbZvxdp5Y4nyTmnhspDwCkgXc2xTtpV+O+0fpKErYQBBosqOElVaOlPK4mTO35DztLBc3Cqy1uK7F3CQiAvXMbqPYl9tf5iYm9W6k/6b9htashuAUixf0TETlox4oSydyinmOWED5ZUYHuI334W16IHse+Y1G9bITuAwf2b53KqL6OPoWi5ZtfzBBELck8ZvZkJ+0Nk6qKwhnINRuf
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
