---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: technical-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAY86E5gVEW6dh0RiHWY0NF9XVzvLZhtZh4EYnTetb0DP3esVglBeNPyM2r9bw3cjJ5FtZWSSgMq7dQH2eW0Qqfvgy1EhrQEPmIAaBqCROVl87xGgYsFK17e7HKddcNJEzDQXQkzl0Zd906dvwN11KnV+42c5T7Gy2AL5GOfCPqYIJG/UZ64wcWxeLrffHG1qE5a9CCyISF65Mn2oJIDbRgJIwgSEVtszUj/t5r60Y8FF0z20Z4hnssOnKV2SZFtOjenOzg+X1SP5Z4H15iFdXsH1ksaaP7JAcVrCsCfAqi9ItaG5mvmFCDt2fJAFLqDu9WdtR2NLw8dcnKQxIUOJo0IjKRCAZTaBmhQhsWMJraePHsCwj65B6Iu1fW0DjVGFY6vayjqAIN5wRpiRwuNWFQzHMwspTxGHahc+UzLvhueUNyVrTYzvYdKg8ZngjS8BTTN5ol2Y4Jjhyu6H7P18MRiBrALvhdBz/1l+iAGk6wPhPEELyV5uUiMARMkLTbVRqhfwYhpar5ULzpXf7BSHYf46Ii8VEEECB/Lt/xpBoDFIaa3pTW3VfRAT3bamKt6sPbPZCth1SdTKeM0rwIdl1Itd8zdEm749NCEtfSzyYP+ILMOJ9okB/A80lmTWfpKaHM5aVo26ejq8sy32jemxyLv3acGe+Ke2KaQmLLEV/pPtQ0goDWljrXlDjiWrUtseGdtl4pYgaNingHJ4dxCiuEQeHt5vvFvd48xlHZMmZcknYWn9bEYVb4khdcOwLywPc5SX7/PeBYgvOThLtgz8FtO2b14rhf5iqITWCyOJTyb5Vo3HZfq/F6arfEYmMM53dbHazTNettTDz9I4JRtd8idIzbj5ZSx/H45zIgoBoz4yTB6q6YQCItf/uLCE0pQdYGwDC3zRwMxiuvFiYcTWEs2Fl9dkGx/oQlsbJYFCDtNdjNBrfaTXPQvlI=
  template:
    metadata:
      creationTimestamp: null
      name: technical-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
